<a href="https://colab.research.google.com/github/AntonisGantzos/Tensorflow-Fundamentals/blob/main/TensorFlow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow Baiscs
Tensorflow consists of 2 main concepts :
  1) Graphs
  2) Sessions

TensorFlow works by building a graph of defined computations as a way of defining all he operations that are written in code.

Sessions allow parts of the graph to be executed.

In [ ]:
%tensorflow_version 2.x #not needed unless we use a notebook. Used to switch the major version to 2.x or 1.x depending on the user's choice

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


#Creating Tensors

In [ ]:
string = tf.Variable("string tensor", tf.string)
number = tf.Variable(123, tf.int16)
float = tf.Variable(12.3, tf.float64)

#Rank/Degree of Tensors
the shape of a ensor is simply the amount of elements that exist in each dimension

In [ ]:
tensor1 = tf.Variable(["string tensor", "t1", "t2"], tf.string) #rank = 1
tensor2 = tf.Variable([["string tensor", "t1"], ["t2","t3"]], tf.string) #rank = 2

tf.rank(tensor1), tf.rank(tensor2)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

#Shape of a tensor
the shape of a tensor is the amount of elements that exist in each dimension

In [ ]:
tf.shape(tensor1), tf.shape(tensor2)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>)

In [ ]:
tensor1 = tf.ones([1,2,3]) #this makes a tensor of the dimensions specified and fills it with 1s
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshapes a given tensor to the defined dimensions
tensor3 = tf.reshape(tensor2, [3, -1]) #-1 tells the tensor to calculate the size of the dimension in that place
#so the tensor is reshaped to [3,2]
tensor4= tf.zeros([5,5,5,5])
tensor5 = tf.reshape(tensor4, [125,-1])
tensor1, tensor2, tensor3,tensor4, tensor5

(<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0.,

#Relative documentation

For more info on tensors and data types check TensorFlow's official documentation site : https://www.tensorflow.org/api_docs/python/tf/dtypes

#Useful functions in TensorFlow


In [ ]:
#convert numpy array to a tensor
import numpy as np
np_array = np.array([1,2,3])
print(f"original numpy array : {np_array}")

#use convert_to_tensor function that takes a numpy arrray as input
converted_tens = tf.convert_to_tensor(np_array)
print(f"converted numpy array to tensor : {converted_tens}")


original numpy array : [1 2 3]
converted numpy array to tensor : [1 2 3]


In [ ]:
#this method creates a diagonal matrix. A diagonal matrix has all its values 0 except the main diagonal
#if number of columns is None a square matrix (rows = cols) is being created by default.
#Batch sets how many extra dimensions the matix will have other than rows X cols
diag_tens = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=[2, 3],
    dtype=tf.dtypes.float32,
    name=None
)

print(diag_tens.shape)
print(diag_tens)


(2, 3, 5, 5)
tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 3, 5, 5), dtype=float32)


In [ ]:
#fill a tensor with values
fill_tensor = tf.fill(
    [2, 4], 9, name=None, layout=None
)

print(fill_tensor)

#this function takes a tensor as input and replaces all its values with 1
one_like_tensor = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)

print(one_like_tensor)

fill_tensor_size = tf.size(
    fill_tensor, out_type=None, name=None
)

fill_tensor_rank = tf.rank(
    fill_tensor, name=None
)

fill_tensor_shape = tf.shape(
    fill_tensor, out_type=None, name=None
)
print(f"the shape of fill_tensor is : {fill_tensor_shape} while its size is {fill_tensor_size} and its rannk is {fill_tensor_rank}")

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]], shape=(2, 4), dtype=int32)
the shape of fill_tensor is : [2 4] while its size is 8 and its rannk is 2


#Differences between shape size and rank

Rank : Number of dimensions of a matrix i.e. a [4, 4] matrix has 2 dimenshions so its rank is 2

Size : the total number of elements in a tensor. Continuing wihthe previous example a [4, 4] tensor has a total of 16 elements so its size is 16

Shape : the shape of each dimension of the tensor

In [ ]:
#create random tensor. all values in the tensor are normally distributed
rand_tensor = tf.random.normal(
   [3,2], mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None

    )

print(rand_tensor)

rand_uniform_tensor = tf.random.uniform(
    [3,2], minval=-1, maxval=1, dtype=tf.dtypes.float32, seed=None, name=None
)

print(rand_uniform_tensor)


tf.Tensor(
[[-1.0390556   0.12523524]
 [-1.0435052   2.1197848 ]
 [ 0.2640635  -0.20963061]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 0.3620844   0.20683074]
 [-0.74345136 -0.6185863 ]
 [-0.41658258 -0.67400455]], shape=(3, 2), dtype=float32)
